add eknitter ip handling
AllYarnsAreBeautiful/ayab-desktop pull request #727
Opened 2024-11-17 17:11 UTC by yekomS

2024-11-17 17:24 UTC, X-sam requested changes
Surface level observation- code does not meet base standards of typing expectations.

2024-11-17 18:58 UTC, dl1com commented
> Surface level observation- code does not meet base standards of typing expectations.

Let's try ...

@coderabbitai suggest changes to establish Python typing on the changed and added code portions, as typing is already established in the rest of our codebase as well.

2024-11-17 22:22 UTC, dl1com commented
@yekomS also, please add some information bout what this PR is for, plus any information which should be added to the manual (i.e. in case there are any compatibility limitations with eKnitter versions or similar)
Thanks a lot, and thanks for the PR!

2024-12-02 12:16 UTC, jpcornil-git commented
Wrt IP handling, why a TCP rather than a websocket connection (assuming desktop becomes a webApp ultimately the latter looks like a more natural/generic approach) ?

2025-04-13 17:52 UTC, dl1com commented
@yekomS the source branch fro this PR seems to have diverted from its initial intention.
It now watches the actions happening on the your local eknitter branch (including changes like flashing to ESP32 etc.).

In case you are still interested in supplying the eKnitter network connectivity to AYAB, please do this on a suitable branch, so we only get the required portions of code for this.

2025-09-15 07:13 UTC, jpcornil-git commented
Note that Websocket is now supported on the main branch  (see #792)/will be included in the next release and so you might consider migrating to it rather than continuing to merge and maintain a raw TCP/UDP protocol (add mdns for discovery and use websocket for data un your esp32 code)

2025-09-15 07:26 UTC, dl1com commented
Closing for now, as this PR seems to be abandoned and we decided for websocket technology in AYAB.
In case there are relevant contributions from eKnitter project, please open a new PR.
Thanks a lot 🙏

2025-09-15 07:26 UTC, closed without merging